GET http://localhost:3000/freejobalert/


### error
GET http://localhost:3000/freejobalert/xyz

###
GET http://localhost:3000/freejobalert/gov/other-all-india-exam

### 
GET http://localhost:3000/freejobalert/bank-jobs/

###
GET http://localhost:3000/freejobalert/teaching-jobs
###
GET http://localhost:3000/freejobalert/engineering-jobs

###
GET http://localhost:3000/freejobalert/railway-jobs

###
GET http://localhost:3000/freejobalert/defence-jobs
###
GET http://localhost:3000/freejobalert/gov/state/AP
### error
GET http://localhost:3000/freejobalert/gov/state/AP89

###
GET http://localhost:3000/freejobalert/gov/state/wb

